### ISSUE TITLE
Can't scroll back through time when viewing portrait camera in nvr on mobile

### ISSUE THREAD

**Issue by cnelson-pdx** [koush/nvr.scrypted.app#6]
I can provide a screenshot if necessary.
Two of my cameras are portrait and record/work fine on desktop as well as in landscape on mobile. 

Behavior could be improved by tapping or pulling up on the camera name to show the timeline and cover half the camera feed to allow for viewing and panning in feed and scrolling timeline.

**Comment by koush** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/73924/229186207-38aeea85-705d-4328-b80a-e85588bc4827.png">

**Comment by koush** [comment]
Fixed. Aspect ratios will be forced to 16:9 or 4:3 range to ensure UI issues like this don't occur.

**Comment by niallobr** [comment]
My Arlo doorbell provides a 1:1 ratio stream. It seems to be getting stretched to 16:9 now. I think the UI was ok before when it appeared square, so maybe 1:1 could be allowed too? Or if it can be shown as 16:9 with black bars either side instead of being stretched out?

**Comment by niallobr** [comment]
Just dropping a tag @koush since this issue is technically closed and my comment above about the 1:1 aspect ratio might have been missed.

**Comment by koush** [comment]
@niallobr can you provide a screenshot

**Comment by niallobr** [comment]
Sure @koush, thank you.

![homekit](https://github.com/koush/nvr.scrypted.app/assets/204252/c214ade5-9054-43b8-9cbe-c69debac6f45)
![nvr2](https://github.com/koush/nvr.scrypted.app/assets/204252/a58a3461-3a85-4dc0-b4fc-ec03ad169b14)
![nvr1](https://github.com/koush/nvr.scrypted.app/assets/204252/21bb8e52-e9c5-418d-a796-d58c1207a164)

**Comment by koush** [comment]
The app has been changed to fit between 16:9 to 4:3. These are common ratios. This is 4:3.

Your 1:1 is also a stretched fov, you can see the fisheye effect.

Unfortunately due to wide variety in camera fov and encoding resolution, choices need to be made or fit into a common ui. I think using common aspect ratio caps is the best solution here.

**Comment by niallobr** [comment]
@koush A fisheye lens is stretched in a uniform manner though. This is stretching the video from 2 sides only which always looks more unnatural than a panoramic effect (like fisheye) to me. I do accept that 1:1 is an unusual aspect ratio to deal with in general though. A good compromise might be if at some point if 1:1 feeds could appear inside the 4:3 or 16:9 frame with black bars either side instead of the stretching. The nearest example I can think of would be how the CSS background-size CSS property works with a contain value set. Attached a mockup of how that might look.

![nvr2-mockup](https://github.com/koush/nvr.scrypted.app/assets/204252/02f0222e-f493-4ece-8d12-4b88ab9ba6be)
